### ISSUE TITLE
cape cod

### ISSUE THREAD

**Issue by rcullito** [rcullito/open-bounty#59]
is too flat and has lots of water

**Comment by commiteth** [comment]
Current balance: 0.000000 ETH
Contract address: [0xac72efeed7b028d97ecac692aa4250acfaf791d5](https://ropsten.etherscan.io/address/0xac72efeed7b028d97ecac692aa4250acfaf791d5)
![QR Code](https://rob-open-bounty.ngrok.io/qr/rcullito/open-bounty/bounty/59/dcd4bf9110b1cf31670978ac8bbcf05b7c74db06eb9ee606aa0f1e96ed84b791/qr.png)
Network: Testnet (Ropsten)
To claim this bounty sign up at [https://rob-open-bounty.ngrok.io](https://rob-open-bounty.ngrok.io) and make sure to update your Ethereum address in `My Payment Details` so that the bounty is correctly allocated.
To fund it, send test ETH or test ERC20/ERC223 tokens to the contract address.
