### ISSUE TITLE
trial with new wallet address

### ISSUE THREAD

**Issue by rcullito** [rcullito/open-bounty#61]
meant as part of investigation for https://github.com/status-im/open-bounty/issues/329

**Comment by commiteth** [comment]
Current balance: 0.000000 ETH
Contract address: [0xf388242db2e6f14507c36b4d28427507478a4926](https://ropsten.etherscan.io/address/0xf388242db2e6f14507c36b4d28427507478a4926)
![QR Code](https://rob-open-bounty.ngrok.io/qr/rcullito/open-bounty/bounty/61/32c2816c70ca248ccb72ca6392a1f3c64e6761eb3dcb25b70389bba0dac3b7ee/qr.png)
Network: Testnet (Ropsten)
To claim this bounty sign up at [https://rob-open-bounty.ngrok.io](https://rob-open-bounty.ngrok.io) and make sure to update your Ethereum address in `My Payment Details` so that the bounty is correctly allocated.
To fund it, send test ETH or test ERC20/ERC223 tokens to the contract address.
